### ISSUE TITLE
Supporting 3.x and Salesforce Graph Engine

### ISSUE THREAD

**Issue by johnbelosf** [packocz/sfdx-code-review-action#1]
Hello,
I am the PM for Salesforce Code Analyzer. First of all many thanks for putting together this GitHub action!
We currently have v3.x of Code Analyzer as an open pilot and I'd like to suggest that your GitHub action supports the new scanner:run:dfa command that is specific to Graph Engine. You can learn more about Graph Engine [here](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/introduction/).
Thank you!

**Comment by packocz** [comment]
Hi @johnbelosf 
Took me a while, but I got there in the end :-) 
I'm still testing a bit and preparing a new blog post, but should be working.
