### ISSUE TITLE
Does not work on ubuntu-latest

### ISSUE THREAD

**Issue by Yurii-Zakharov** [packocz/sfdx-code-review-action#5]
With this configuration:
    - name: Code Review
      uses: packocz/sfdx-code-review-action@v0.3.0
      with:
          reject_threshold: 1
          max_comments: 20
          engine: 'pmd'
          pmdconfig: sfdx-scanner/my-ruleset-pmd.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

Throw next error:
Error: Dependencies lock file is not found in /home/runner/work/my-repo/my-repo. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock

**Comment by packocz** [comment]
@Yurii-Zakharov sorry, I completely missed this issue. Probably too late, but in case you're still having issues / are interested, can you share your full .yml file? I'm not having any issues like that running the same config on 'ubuntu-latest'.
